name: Python Script Execution

on:
  schedule:
  - cron: 10 */2 * * *

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Set the Python version as per your script's requirements

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Replace with your script's dependencies

    - name: Execute Python script
      run: python detect_qpe_outages.py # Replace with the path to your script
      env:
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
        INFLUX_TOKEN_PROD_READ: ${{ secrets.INFLUX_TOKEN_PROD_READ }}
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
